version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: auth-service
    ports:
      - 3001:3001
      - 9229:9229
    environment:
      - MONGO_URI=mongodb://mongo:27017/cms
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - JWT_SECRET=462D4A614E645267556A586E3272357538782F413F4428472B4B625065536856
      - REFRESH_SECRET=6150645367556B58703273357638792F423F4528482B4D6251655468576D5971
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - mongo
      - redis
    networks:
      - app-network
      - database-network
    command: ["npm", "run", "debug"]
  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db
    networks:
      - database-network
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
    networks:
      - database-network
  mongo-express:
    image: mongo-express:latest
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
    depends_on:
      - app
    networks:
      - database-network
  reverse-proxy:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
    networks:
      - app-network
volumes:
  mongo_data:
  redis_data:

networks:
  app-network:
    driver: bridge
  database-network:
    driver: bridge
